apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livekit-webhook-proxy.fullname" . }}-config
  labels:
    {{- include "livekit-webhook-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}