name: Build
on:
    push:
        tags:
            - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        - name: 'Build Inventory Image'
          run: |
            docker build . --tag ghcr.io/${{ env.GITHUB_REPOSITORY }}:${{ github.ref_name }}
            docker push ghcr.io/${{ env.GITHUB_REPOSITORY }}:${{ github.ref_name }}