# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
  push:
    branches: 
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    
    - uses: gwatts/go-coverage-action@v1
      id: coverage
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        coverage-threshold: 80

        # collect coverage for all packages beyond the one under test
        cover-pkg: ./...
        
    - name: Go Dependency Submission
      uses: actions/go-dependency-submission@v1
      with:
        # Build target to detect build dependencies. If unspecified, will use "all", with will detect all dependencies used in all build targets (including tests and tools).
        go-build-target: main.go
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
